"""routes/reports.py — DGMS-format compliance report generation."""
import io
from datetime import date
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse, JSONResponse
from sqlalchemy.orm import Session
from sqlalchemy import func

from database import get_db
from auth import get_current_officer
import models

router = APIRouter(
    prefix="/reports",
    tags=["Reports"],
    dependencies=[Depends(get_current_officer)],
)


def _generate_pdf(worker: models.Worker, readings: list, report_date: str) -> bytes:
    """Generate a DGMS-compliant PDF exposure report using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=2*cm, rightMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Heading1"],
                                  alignment=TA_CENTER, fontSize=14, spaceAfter=6)
    subtitle_style = ParagraphStyle("sub", parent=styles["Normal"],
                                     alignment=TA_CENTER, fontSize=10, spaceAfter=12)
    header_style = ParagraphStyle("header", parent=styles["Heading2"], fontSize=11, spaceAfter=4)

    story = []

    # Header
    story.append(Paragraph("DIRECTORATE GENERAL OF MINES SAFETY (DGMS)", title_style))
    story.append(Paragraph("H2S Exposure Monitoring Compliance Report", subtitle_style))
    story.append(Paragraph(f"Report Date: {report_date}   |   Generated by: H2S Dosimeter System v1.0", subtitle_style))
    story.append(Spacer(1, 0.5*cm))

    # Worker Info
    story.append(Paragraph("Worker Information", header_style))
    info_data = [
        ["Worker ID", worker.worker_id, "Full Name", worker.full_name],
        ["Department", worker.department or "—", "Site", worker.site or "—"],
        ["Designation", worker.designation or "—", "Shift", worker.shift or "—"],
    ]
    info_table = Table(info_data, colWidths=[3.5*cm, 5.5*cm, 3.5*cm, 5.5*cm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.lightgrey),
        ("BACKGROUND", (2,0), (2,-1), colors.lightgrey),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("PADDING", (0,0), (-1,-1), 4),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.5*cm))

    # DGMS thresholds reference
    story.append(Paragraph("Applicable DGMS Limits", header_style))
    limits_data = [
        ["Parameter", "Limit", "Status Colour"],
        ["TWA (8-hr average)", "10 ppm", "—"],
        ["STEL (15-min short-term)", "15 ppm", "—"],
        ["Cumulative Dose Alert", "60 ppm.hr (Warning)", "Orange"],
        ["Cumulative Dose Limit", "80 ppm.hr (Danger)", "Red"],
        ["Immediate Evacuation", "100 ppm.hr (Critical)", "Dark Red"],
    ]
    limits_table = Table(limits_data, colWidths=[6*cm, 5*cm, 7*cm])
    limits_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("PADDING", (0,0), (-1,-1), 4),
    ]))
    story.append(limits_table)
    story.append(Spacer(1, 0.5*cm))

    # Readings table
    story.append(Paragraph(f"Exposure Readings ({len(readings)} records)", header_style))
    table_data = [["#", "Timestamp", "Dose (ppm.hr)", "DeltaE", "Temp (C)", "Humidity (%)", "Status"]]

    for i, r in enumerate(readings, 1):
        dose = r.dose_ppm_hr
        if dose >= 100:
            status_str = "CRITICAL"
            row_color = colors.HexColor("#ffcccc")
        elif dose >= 80:
            status_str = "DANGER"
            row_color = colors.HexColor("#ffd6a5")
        elif dose >= 60:
            status_str = "WARNING"
            row_color = colors.HexColor("#fff3cd")
        else:
            status_str = "SAFE"
            row_color = colors.white

        ts = r.scan_timestamp.strftime("%Y-%m-%d %H:%M") if r.scan_timestamp else "—"
        table_data.append([
            str(i), ts, f"{dose:.2f}",
            f"{r.delta_E:.3f}" if r.delta_E else "—",
            f"{r.temperature_c:.1f}" if r.temperature_c else "—",
            f"{r.humidity_pct:.1f}" if r.humidity_pct else "—",
            status_str,
        ])

    col_widths = [1*cm, 4*cm, 3*cm, 2.5*cm, 2.5*cm, 2.5*cm, 2.5*cm]
    readings_table = Table(table_data, colWidths=col_widths)

    # Build row-specific styles
    table_style = [
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 8),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("ALIGN", (2,0), (-1,-1), "CENTER"),
        ("PADDING", (0,0), (-1,-1), 3),
    ]
    for i, r in enumerate(readings, 1):
        dose = r.dose_ppm_hr
        if dose >= 100:
            table_style.append(("BACKGROUND", (0,i), (-1,i), colors.HexColor("#ffcccc")))
        elif dose >= 80:
            table_style.append(("BACKGROUND", (0,i), (-1,i), colors.HexColor("#ffd6a5")))
        elif dose >= 60:
            table_style.append(("BACKGROUND", (0,i), (-1,i), colors.HexColor("#fff3cd")))

    readings_table.setStyle(TableStyle(table_style))
    story.append(readings_table)
    story.append(Spacer(1, 0.5*cm))

    # Summary stats
    if readings:
        doses = [r.dose_ppm_hr for r in readings]
        max_dose = max(doses)
        avg_dose = sum(doses) / len(doses)
        story.append(Paragraph("Summary", header_style))
        summary_data = [
            ["Total Readings", str(len(readings))],
            ["Maximum Dose", f"{max_dose:.2f} ppm.hr"],
            ["Average Dose", f"{avg_dose:.2f} ppm.hr"],
            ["DGMS Compliance", "NON-COMPLIANT" if max_dose >= 80 else "COMPLIANT"],
        ]
        summary_table = Table(summary_data, colWidths=[5*cm, 6*cm])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (0,-1), colors.lightgrey),
            ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("PADDING", (0,0), (-1,-1), 4),
        ]))
        story.append(summary_table)

    story.append(Spacer(1, 1*cm))
    story.append(Paragraph("This report is auto-generated by the SIH H2S Dosimeter System (SIH26118).", styles["Normal"]))

    doc.build(story)
    buf.seek(0)
    return buf.read()


@router.get("/worker/{worker_id}/pdf")
def get_worker_report_pdf(
    worker_id: str,
    shift_date: Optional[str] = None,
    db: Session = Depends(get_db),
):
    """Download a DGMS-format PDF compliance report for a worker."""
    worker = db.query(models.Worker).filter(models.Worker.worker_id == worker_id).first()
    if not worker:
        raise HTTPException(status_code=404, detail=f"Worker '{worker_id}' not found.")

    q = db.query(models.Reading).filter(models.Reading.worker_id == worker.id)
    if shift_date:
        q = q.filter(models.Reading.shift_date == shift_date)
    readings = q.order_by(models.Reading.scan_timestamp.asc()).all()

    report_date = shift_date or date.today().isoformat()
    pdf_bytes = _generate_pdf(worker, readings, report_date)

    filename = f"DGMS_Report_{worker_id}_{report_date}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/worker/{worker_id}/json")
def get_worker_report_json(
    worker_id: str,
    shift_date: Optional[str] = None,
    db: Session = Depends(get_db),
):
    """Get report data as JSON (used by dashboard charts)."""
    worker = db.query(models.Worker).filter(models.Worker.worker_id == worker_id).first()
    if not worker:
        raise HTTPException(status_code=404, detail=f"Worker '{worker_id}' not found.")

    q = db.query(models.Reading).filter(models.Reading.worker_id == worker.id)
    if shift_date:
        q = q.filter(models.Reading.shift_date == shift_date)
    readings = q.order_by(models.Reading.scan_timestamp.asc()).all()

    doses = [r.dose_ppm_hr for r in readings]
    return {
        "worker_id": worker_id,
        "full_name": worker.full_name,
        "site": worker.site,
        "shift": worker.shift,
        "shift_date": shift_date or date.today().isoformat(),
        "total_readings": len(readings),
        "max_dose_ppm_hr": max(doses) if doses else 0,
        "avg_dose_ppm_hr": round(sum(doses)/len(doses), 3) if doses else 0,
        "dgms_compliant": max(doses) < 80 if doses else True,
        "readings": [
            {
                "id": r.id,
                "timestamp": r.scan_timestamp.isoformat() if r.scan_timestamp else None,
                "dose_ppm_hr": r.dose_ppm_hr,
                "delta_E": r.delta_E,
                "temperature_c": r.temperature_c,
                "humidity_pct": r.humidity_pct,
            }
            for r in readings
        ],
    }
